### PR TITLE
Fix various issues

### PR DESCRIPTION
**Pull request by nikazooz**
Hey there! :wave: 

There seem to be some issues with the latest version. Here's a PR to fix them.

Fixes https://github.com/cpriego/valet-linux/issues/245
Fixes https://github.com/cpriego/valet-linux/issues/244
Fixes https://github.com/cpriego/valet-linux/issues/242

- Context cannot be bound to static closures. When commands are created in Silly those closures are bound to command objects
- Default value shouldn't be set on options that are used as a flags. They will have value of `false` if not present and value of `true` if present.

P.S. Thanks for the great project! :slightly_smiling_face:

### CODE REVIEW

**Comment by goldcoders** [comment]
can someone already merge this?

**Comment by goldcoders** [comment]
i tried using your PR , but it seems it doesnt work as well on arch
```
PHP Warning:  require(/home/uriah/.config/composer/vendor/composer/../symfony/polyfill-php72/bootstrap.php): failed to open stream: No such file or directory in /home/uriah/.config/composer/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  require(): Failed opening required '/home/uriah/.config/composer/vendor/composer/../symfony/polyfill-php72/bootstrap.php' (include_path='.:') in /home/uriah/.config/composer/vendor/composer/autoload_real.php on line 66

```

**Comment by tgosp** [comment]
The fix solves #244 
Confirmed with 

> PHP 7.3.12-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Nov 28 2019 07:37:16) ( NTS )

> Description:	Linux Mint 19.2 Tina
> Release:	19.2
> Codename:	tina

**Comment by jmarcher** [comment]
Merged and tagged v2.2.4

**Pull request merged**
