### PR TITLE
Sync ValetDrivers with upstream, add support for LocalValetDriver

### PR DESCRIPTION
**Pull request by dakira**
There were some useful additions to Valet (specifically Magento, Neos and Typo3 drivers) and updates to existing drivers. I updated the drivers to be in sync with upstream without applying changes that haven't been implemented in valet-linux.

This also adds support for project-specific drivers.

### CODE REVIEW

**Comment by cpriego** [comment]
Thanks so much for taking the time to add this.

**Comment by dakira** [comment]
@cpriego sure. Is there any interest in updating the rest of valet-linux to be in sync with valet-vanilla? The way I see it the only difference should be setting up the DNS resolving and installing the packages. Everything else should work without problems.

**Comment by cpriego** [comment]
Hi @dakira, what else should be updated to be in sync with laravel/valet

I'm asking because some customizations were done to the code so it works better in linux.

**Comment by dakira** [comment]
There are many commits in laravel/valet that are not platform-specific. This one for instance:
https://github.com/laravel/valet/commit/6727e43288a8b29ce0151de44ca192e1c8592051

**Comment by dakira** [comment]
@cpriego I take the *many* back. ;) Just went through the whole diff. There are *some* more things I'd sync, but rather many things that should be taken from valet-linux to the original valet. ;-)

**Comment by cpriego** [comment]
Hahahaha don't worry @dakira, I'd love to see those "some" things you would sync and, indeed, we've added some features we think are *really* needed in laravel/valet.

**Comment by entr** [comment]
https://github.com/laravel/valet/commit/27b7ecebf58d3bcb8d3be88dfadd3cbe2530395c might be missing too.

So you don't actually rely on the git tree to stay in sync with upstream? A manual diff and patch is enough, right?

**Comment by dakira** [comment]
@entr can you create an issue or a pull request for this? This one is merged already.

**Pull request merged**
