### PR TITLE
Add support for Solus Package Manager - eopkg

### PR DESCRIPTION
**Pull request by ivanlogiudice**
Related to https://github.com/cpriego/valet-linux/issues/125.

Todo:
- php-fpm come inside the package php (filter package name?)
- There is some problems with dnsmasq

### CODE REVIEW

**Comment by abrhambas01** [comment]
I can't seem to work with php-fpm ? does this have any issues with it ? 

image

**Comment by jmarcher** [comment]
@ivanlogiudice Can you provide more information about this?

**Comment by slave2anubis** [comment]
Hello, you can try out my fork, it will run on Solus 4 without any problems, but after restart you need to restart the "valet-dns" service since there seems to be a problem with it...
Restart command: sudo systemctl restart valet-dns

https://github.com/slave2anubis/valet-linux

**Comment by jmarcher** [comment]
@slave2anubis Do you think you could make a PR? @ivanlogiudice does not seem to respond and I do not use a distro with this package manager.

**Comment by slave2anubis** [comment]
@jmarcher i modified the repo ONLY to work on Solus 4... I dont have the time/skill to integrate it with the main repo.

**Comment by jmarcher** [comment]
@slave2anubis Do you mind doing a code review of this PR?

**Comment by slave2anubis** [comment]
@jmarcher Can you be more specific?

**Comment by jmarcher** [comment]
I'm not familiar with eopkg, if you could take a look at this PR and make a
quick code review and see if everything works.


Dacian Bujor <notifications@github.com> schrieb am Sa., 1. Juni 2019, 11:58:

**Comment by slave2anubis** [comment]
@jmarcher Hello again, i made some more improvements to the package... and now you can install it without errors...
But there is still a problem with the valet-dns service, in that after a boot/reboot it does not "watch" the network-manager folders and does not update the dns files, so you need to manually issue a "sudo systemctl restart valet-dns" command to be able to get any dns working on your system.
I tried to fix this, but i am not able to comprehend how the "inotifywait" works exactly, since i think this is the culprit.
Any help would be apreciated.

**Pull request merged**
