### PR TITLE
fix static files path issues with some of latest versions

### PR DESCRIPTION
**Pull request by AboElnoor**
**Related Issue:**
https://github.com/cpriego/valet-linux/issues/227

### CODE REVIEW

**Comment by jmarcher** [comment]
Yes, we need to check if this change breaks old Magento installations, if this is the case we should come up with a solution for both versions.

**Comment by jmarcher** [comment]
@AboElnoor do you have any feedback on this?

**Comment by AboElnoor** [comment]
> @AboElnoor do you have any feedback on this?

I've just checked 2.3.1, 2.3.2.
I'm early Magento developer and don't have previous versions

**Comment by AboElnoor** [comment]
https://github.com/cpriego/valet-linux/commit/680b7e13e4b098e56b66bd0614b86bcffc6ea911#diff-c332cd538cd7d3131e36c43512b648be
The above commit was an update, and it doesn't mention fixing old issues.
Maybe that update was working fine with old versions, but not applied to new versions, that's why I think that is an important change to fix the new issue.

**Pull request merged**
