### PR TITLE
fix: infinite loop on guessing PHP service name

### LINKED ISSUE #377: Getting PHP service name causes infinite loop
When running `valet install`, `valet secure` or `valet unsecure`, it causes an infinite loop on this line:

https://github.com/cpriego/valet-linux/blob/d132f709eb066941a673511d869a9902b214b17c/cli/Valet/PhpFpm.php#L236

It will hang on "Restarting php-fpm" because of this.

### PR DESCRIPTION
**Pull request by codepuncher**
Fixes #377

### CODE REVIEW

**Comment by codepuncher** [comment]
Note: looking at latest changes in `master`, this may be redundant.

**Comment by PH7-Jack** [comment]
It fixes https://github.com/cpriego/valet-linux/issues/402 on arch linux

**Comment by codepuncher** [comment]
@Adesin-fr please can you review this? I know that the PR is quite outdated from your latest changes, but fundamentally this solves the underlying issue of PHP package names being inconsistent between distributions.

**Comment by jmarcher** [comment]
Merged in b0830ea3eacde1f8d920a4c90cdc67ba65cfddcd (needed to resolve the conflicts)

**Pull request closed without merging**
